trigger: none

pool:
  name: Doctor Agent Pool

variables:
- group: aws-secrets

- name: AZURE_SUBSCRIPTION
  value: Doctor Project Service Connection

- name: ECR_REPO_URI
  value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/doctor-app

- name: IMAGE_TAG
  value: latest

- name: DEV_APP_NAME
  value: doctor-dev-app

- name: QA_APP_NAME
  value: doctor-qa-app

- name: UAT_APP_NAME
  value: doctor-uat-app

- name: PROD_APP_NAME
  value: doctor-prod-app

stages:

- stage: Deploy_DEV
  jobs:
  - deployment: Dev
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              appName: $(DEV_APP_NAME)
              containers: '$(ECR_REPO_URI):$(IMAGE_TAG)'

- stage: Deploy_QA
  dependsOn: Deploy_DEV
  jobs:
  - deployment: QA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              appName: $(QA_APP_NAME)
              containers: '$(ECR_REPO_URI):$(IMAGE_TAG)'

- stage: Deploy_UAT
  dependsOn: Deploy_QA
  jobs:
  - deployment: UAT
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              appName: $(UAT_APP_NAME)
              containers: '$(ECR_REPO_URI):$(IMAGE_TAG)'

- stage: Deploy_PROD
  dependsOn: Deploy_UAT
  jobs:
  - deployment: PROD
    environment: PROD
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              appName: $(PROD_APP_NAME)
              containers: '$(ECR_REPO_URI):$(IMAGE_TAG)'
